stages:
  load_data:
    cmd : python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - config/config.yaml
      - src/utils/all_utils.py
    outs:
      -  artifacts/raw_local_dir/data.csv

  split_data:
    cmd : python src/stage_02_split_save.py --config=config/config.yaml --params=params.yaml
    deps:
    - src/stage_02_split_save.py 
    - config/config.yaml
    - src/utils/all_utils.py
    - artifacts/raw_local_dir/data.csv
    params:
    - base.random_state
    - base.test_size
    outs:
    - artifacts/split_data_dir/train.csv
    - artifacts/split_data_dir/test.csv

  training_stage:
    cmd : python src/stage_03_train.py --config=config/config.yaml --params=params.yaml
    deps:
    - src/stage_03_train.py 
    - config/config.yaml
    - src/utils/all_utils.py
    - artifacts/split_data_dir/train.csv
    params:
    - base.random_state
    - model_params.ElasticNet.alpha
    - model_params.ElasticNet.l1_ratio
    outs:
    - artifacts/model_dir/ElasticNet.model

  evaluation_stage:
    cmd : python src/stage_04_evaluate.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_04_evaluate.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/test.csv
      - artifacts/model_dir/ElasticNet.model
    outs:
      - artifacts/reports_dir/scores.json  

      


