# data_source : where the data is stored ....
# raw_local_file: whatever file downloding call it as data.csv
# 
# raw_local_dir: raw_local_dir

data_source: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts: 
  artifacts_dir: artifacts    # save dataset inthis dir 
  raw_local_dir: raw_local_dir    # child dir of artifact 
  raw_local_file: data.csv        # store file with name 




